name: build-and-push-ecr

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    # 1) Checkout code
    - uses: actions/checkout@v4

    # 2) Enable cross-platform builds
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    # 3) Log in to ECR (uses your secrets)
    - uses: aws-actions/amazon-ecr-login@v2
      with:
        region: ${{ secrets.AWS_REGION }}
        mask-password: true

    # 4) Build for amd64 + arm64, push to latest tag
    - name: Build & push
      uses: docker/build-push-action@v5
      with:
        context: ./app           # Dockerfile lives here
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/datadash:latest

