name: build-and-push-ecr

on:
  push:
    branches: [ main ]       # every commit to main triggers a build

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    # ────────────────────────────────────────────────────────────────
    # 1) Checkout repository
    - name: Checkout code
      uses: actions/checkout@v4

    # 2) Enable cross-platform emulation & buildx builder
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # ────────────────────────────────────────────────────────────────
    # 3) Configure AWS credentials **(gets keys from repo secrets)**
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ secrets.AWS_REGION }}

    # 4) Log in to Amazon ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: true

    # ────────────────────────────────────────────────────────────────
    # 5) Build the Docker image and push to ECR
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .                 # folder containing your Dockerfile
        file: ./Dockerfile 
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/datadash:latest
